---
####################################################
#--------------------------------------------------#
# last configuration & cleaning on machine
# |_ change default shell for user
# |_ Theme LightDM
# |_ Ensure font are loaded
# |_ Cleaning package
# |_ reboot if tagged


# - name: Configure LightDM a refaire avec la bonne regex
#   block:
#     - name: Editing LightDM Conf File
#       lineinfile:
#         path: /etc/lightdm/lightdm.conf
#         regexp: "\[Seat\*\]"
#         line: "\[Seat\*\]\ngreeter-session=nody-greeter"
#   tags:
#    - privileged

- name: Changing default shell
  user:
    name: "{{ the_user }}"
    shell: /usr/bin/zsh
    state: present
  tags:
   - privileged

- name: Reboot
  command: reboot
  tags:
    - privileged
    - unpriveged
    - never
    - reboot


