---
- name: Update system before install and install building dependecies
  hosts: localhost

  tasks:
  - name: Update system
    ansible.builtin.apt:
      update_cache: yes

  - name: Install building dependencies
    ansible.builtin.apt:
      name:
        - "build-essential"
        - "psmisc"
      state: latest

- name: Install Rice Dependencies
  hosts: localhost

  tasks:
  - name: Install minimal xserver
    shell: sudo apt-get install xfonts-base xserver-xorg-input-all xinit xserver-xorg-video-all

  - name: Install login page
    shell: sudo apt-get install lightdm
