#!/bin/bash

# Terminate already running bar instances
killall -q polybar

if type "xrandr"; then
    for m in $(xrandr --query | grep "connected" | cut -d" " -f1); do
        MONITOR=$m polybar --reload mybar &
    done
else
    polybar --reload mybar &
fi

# Launch Polybar, using default config location ~/.config/polybar/config.ini
polybar mybar 2>&1 | tee -a /tmp/polybar.log & disown
polybar bartwo 2>&1 | tee -a /tmp/polybar.log & disown
# polybar brokentwo 2>&1 | tee -a /tmp/polybar.log & disown
# polybar broken 2>&1 | tee -a /tmp/polybar.log & disown
# polybar brokenthree 2>&1 | tee -a /tmp/polybar.log & disown

